/* ============================================================================
 * course.config.js — THE ONLY FILE MOST DEPLOYMENTS NEED TO EDIT.
 *
 * Everything below is configuration, not code. Change the values, reload the
 * page. You do not need to touch any other .js file to run your own course.
 *
 * ALL DATE-TIMES ARE WALL-CLOCK LOCAL TIME IN `timezone`, written as
 * "YYYY-MM-DDTHH:mm". Do NOT append "Z" or an offset like "+03:00".
 * The portal converts them to real instants using `timezone`, and the database
 * does the same conversion with the same timezone name, so the browser and the
 * server always agree — including across daylight-saving changes.
 * ==========================================================================*/

var COURSE_CONFIG = {

  /* ---- Identity ------------------------------------------------------- */
  courseName: 'Introductory Short Course',
  courseShortName: 'Short Course',
  organisation: 'Your Institution',
  contactEmail: 'course-admin@example.org',

  /* ---- Interface ------------------------------------------------------ */
  // 'en' (left-to-right) or 'ar' (right-to-left). Add more in src/i18n.js.
  language: 'en',

  /* ---- Time ----------------------------------------------------------- */
  // An IANA timezone name, e.g. 'Africa/Cairo', 'Asia/Riyadh', 'Europe/London',
  // 'America/New_York'. This SAME string must be stored in the database
  // (SETUP.md step 4). Never use a fixed offset such as '+03'.
  timezone: 'Africa/Cairo',

  /* ---- Participant codes ---------------------------------------------- */
  // Codes are generated BY THE SERVER as PREFIX-0001, PREFIX-0002, ...
  // Learners never type or choose their code.
  participantCodePrefix: 'CP',

  /* ---- Course days (1 to 5) ------------------------------------------- */
  // Add or remove entries to change the length of the course. Nothing in the
  // code assumes any particular number of days.
  days: [
    { index: 1, title: 'Day 1 — Foundations',   date: '2026-09-07' },
    { index: 2, title: 'Day 2 — Core Methods',  date: '2026-09-08' },
    { index: 3, title: 'Day 3 — Applications',  date: '2026-09-09' }
  ],

  /* ---- Component windows ---------------------------------------------- *
   * Each component may be open by a time window, and may additionally be
   * force-closed or force-opened by an administrator from the admin console.
   *
   * Effective state = (admin override, if set) else (time window).
   * ---------------------------------------------------------------------*/
  windows: {
    registration: { opensAt: '2026-08-01T00:00', closesAt: '2026-09-09T23:59' },
    pre:          { opensAt: '2026-09-01T00:00', closesAt: '2026-09-07T09:30' },
    post:         { opensAt: '2026-09-09T13:00', closesAt: '2026-09-12T23:59' },
    feedback:     { opensAt: '2026-09-09T13:00', closesAt: '2026-09-12T23:59' },

    // Per-day attendance check-in windows, keyed 'attendance_<dayIndex>'.
    // Keep one entry per entry in `days` above.
    attendance_1: { opensAt: '2026-09-07T08:00', closesAt: '2026-09-07T10:30' },
    attendance_2: { opensAt: '2026-09-08T08:00', closesAt: '2026-09-08T10:30' },
    attendance_3: { opensAt: '2026-09-09T08:00', closesAt: '2026-09-09T10:30' }
  },

  /* ---- Certificate rule ----------------------------------------------- *
   * Eligibility is computed on the SERVER (a database view) and mirrored by
   * identical local logic in demo mode. The learner cannot influence it.
   * ---------------------------------------------------------------------*/
  certificate: {
    // Which components must be completed. Any of: 'registration','pre','post','feedback'
    requiredComponents: ['registration', 'pre', 'post', 'feedback'],
    // Minimum number of days the learner must have checked in for.
    minAttendanceDays: 2,
    // Optional minimum post-test score, as a percentage (0-100). null = no cut-off.
    minPostScorePercent: null
  },

  /* ---- Registration fields -------------------------------------------- *
   * `fullName`, `email` and `password` are always collected and are not listed
   * here. Everything below is optional demographic data; delete what you do
   * not need, add what you do. `key` becomes the column name in the exports.
   *
   * type: 'text' | 'number' | 'select' | 'tel'
   * identifier: true  -> treated as a DIRECT IDENTIFIER; appears only in the
   *                      operations export, never in the research export.
   * ---------------------------------------------------------------------*/
  registrationFields: [
    { key: 'phone',       label: 'Mobile number',   type: 'tel',    required: false, identifier: true },
    { key: 'affiliation', label: 'Affiliation',     type: 'text',   required: true },
    { key: 'role',        label: 'Current role',    type: 'select', required: true,
      options: ['Student', 'Trainee', 'Practitioner', 'Educator', 'Researcher', 'Other'] },
    { key: 'years_exp',   label: 'Years of experience', type: 'number', required: false },
    { key: 'gender',      label: 'Gender',          type: 'select', required: false,
      options: ['Female', 'Male', 'Prefer not to say'] }
  ],

  /* ---- Results & review ----------------------------------------------- */
  // Show the learner an immediate pre-vs-post report after they submit the post-test.
  showImmediateResults: true,
  // Include a per-item review (their answer, the correct answer) in that report.
  showPerItemReview: true,
  // Show the learner their pre-test score straight after the pre-test.
  // Usually FALSE: revealing pre-test answers before teaching contaminates the post-test.
  showPreTestScore: false,

  /* ---- Content files --------------------------------------------------- */
  // Editable CSV files. See content/README.md for the column specification.
  questionsFile: 'content/questions.csv',
  feedbackFile:  'content/feedback.csv',

  /* ---- Backend --------------------------------------------------------- */
  // 'auto'  -> use Supabase if config.js provides real credentials, else demo mode
  // 'demo'  -> always demo mode (browser localStorage only, no server)
  // 'supabase' -> always Supabase; refuse to start without credentials
  backend: 'auto'
};

if (typeof module !== 'undefined' && module.exports) module.exports = COURSE_CONFIG;
if (typeof globalThis !== 'undefined') globalThis.COURSE_CONFIG = COURSE_CONFIG;
